"""add_composite_performance_indexes

Revision ID: 13a783473873
Revises: d1522e8c9757
Create Date: 2026-06-12 23:14:44.393390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13a783473873'
down_revision = 'd1522e8c9757'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index('ix_order_items_order_item_status', ['order_id', 'item_id', 'status'], unique=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index('ix_orders_branch_status_opened_at', ['branch_id', 'status', 'opened_at'], unique=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index('ix_payments_order_paid_method', ['order_id', 'paid_at', 'method'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index('ix_payments_order_paid_method')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('ix_orders_branch_status_opened_at')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index('ix_order_items_order_item_status')

    # ### end Alembic commands ###
