"""add image paths

Revision ID: 13bed8d78211
Revises: 24de33dcbb97
Create Date: 2026-06-10 23:08:49.234158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13bed8d78211'
down_revision = '24de33dcbb97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=255), nullable=True))

    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
