"""initial 26 table schema

Revision ID: 24de33dcbb97
Revises: 
Create Date: 2026-06-10 22:15:49.698609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24de33dcbb97'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('log_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('table_name', sa.String(length=50), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('old_values', sa.Text(), nullable=True),
    sa.Column('new_values', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('branches',
    sa.Column('branch_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('branch_id')
    )
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('customers',
    sa.Column('customer_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('points_balance', sa.Integer(), nullable=True),
    sa.Column('total_spent_cents', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('customer_id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('email_templates',
    sa.Column('template_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('trigger_event', sa.String(length=50), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('is_active', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('template_id')
    )
    op.create_table('modifiers',
    sa.Column('modifier_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=True),
    sa.Column('group_name', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('modifier_id')
    )
    op.create_table('email_logs',
    sa.Column('email_log_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('reference_type', sa.String(length=30), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['email_templates.template_id'], name='fk_emaillog_template'),
    sa.PrimaryKeyConstraint('email_log_id')
    )
    op.create_table('email_recipients',
    sa.Column('recipient_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('recipient_type', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_subscribed', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.branch_id'], name='fk_emailrec_branch'),
    sa.PrimaryKeyConstraint('recipient_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('employees',
    sa.Column('employee_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('email_verified', sa.SmallInteger(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.SmallInteger(), nullable=True),
    sa.Column('hired_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.branch_id'], name='fk_emp_branch'),
    sa.PrimaryKeyConstraint('employee_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ingredients',
    sa.Column('ingredient_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('qty_in_stock', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('reorder_level', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('cost_per_unit_cents', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.branch_id'], name='fk_ingredient_branch'),
    sa.PrimaryKeyConstraint('ingredient_id')
    )
    op.create_table('kds_stations',
    sa.Column('station_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.branch_id'], name='fk_kds_branch'),
    sa.PrimaryKeyConstraint('station_id')
    )
    op.create_table('menu_items',
    sa.Column('item_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('tax_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_available', sa.SmallInteger(), nullable=True),
    sa.Column('is_active', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], name='fk_menuitem_category'),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('offline_sync_logs',
    sa.Column('sync_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('client_uuid', sa.String(length=36), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('sync_status', sa.String(length=15), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.branch_id'], name='fk_offsync_branch'),
    sa.PrimaryKeyConstraint('sync_id'),
    sa.UniqueConstraint('client_uuid')
    )
    op.create_table('printer_configs',
    sa.Column('printer_config_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('printer_role', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('profile', sa.String(length=50), nullable=True),
    sa.Column('is_enabled', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.branch_id'], name='fk_printer_branch'),
    sa.PrimaryKeyConstraint('printer_config_id')
    )
    op.create_table('restaurant_tables',
    sa.Column('table_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('table_number', sa.String(length=10), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.branch_id'], name='fk_table_branch'),
    sa.PrimaryKeyConstraint('table_id'),
    sa.UniqueConstraint('branch_id', 'table_number', name='uq_branch_table')
    )
    op.create_table('email_verifications',
    sa.Column('verify_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('token_type', sa.String(length=20), nullable=True),
    sa.Column('is_used', sa.SmallInteger(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name='fk_emailver_employee'),
    sa.PrimaryKeyConstraint('verify_id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('inventory_count_sessions',
    sa.Column('session_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('session_name', sa.String(length=100), nullable=True),
    sa.Column('started_by', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.branch_id'], name='fk_invsession_branch'),
    sa.ForeignKeyConstraint(['started_by'], ['employees.employee_id'], name='fk_invsession_emp'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('item_ingredients',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('qty_used', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.ingredient_id'], name='fk_ii_ingredient'),
    sa.ForeignKeyConstraint(['item_id'], ['menu_items.item_id'], name='fk_ii_menuitem'),
    sa.PrimaryKeyConstraint('item_id', 'ingredient_id', name='pk_item_ingredients')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('order_type', sa.String(length=15), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('pax', sa.Integer(), nullable=True),
    sa.Column('discount_cents', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('seat_count', sa.Integer(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.branch_id'], name='fk_order_branch'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name='fk_order_employee'),
    sa.ForeignKeyConstraint(['table_id'], ['restaurant_tables.table_id'], name='fk_order_table'),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('print_logs',
    sa.Column('print_log_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('printer_config_id', sa.Integer(), nullable=True),
    sa.Column('reference_type', sa.String(length=30), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.branch_id'], name='fk_printlog_branch'),
    sa.ForeignKeyConstraint(['printer_config_id'], ['printer_configs.printer_config_id'], name='fk_printlog_printer'),
    sa.PrimaryKeyConstraint('print_log_id')
    )
    op.create_table('reservations',
    sa.Column('reservation_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('customer_phone', sa.String(length=20), nullable=True),
    sa.Column('party_size', sa.Integer(), nullable=False),
    sa.Column('reserved_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.branch_id'], name='fk_res_branch'),
    sa.ForeignKeyConstraint(['table_id'], ['restaurant_tables.table_id'], name='fk_res_table'),
    sa.PrimaryKeyConstraint('reservation_id')
    )
    op.create_table('stock_batches',
    sa.Column('batch_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.Column('qty_received', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('qty_remaining', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('cost_per_unit_cents', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('supplier_ref', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.ingredient_id'], name='fk_stockbatch_ingredient'),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_table('user_sessions',
    sa.Column('session_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('session_token', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name='fk_usersession_employee'),
    sa.PrimaryKeyConstraint('session_id'),
    sa.UniqueConstraint('session_token')
    )
    op.create_table('waste_logs',
    sa.Column('waste_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_cost_cents', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.branch_id'], name='fk_wastelog_branch'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.ingredient_id'], name='fk_wastelog_ingredient'),
    sa.ForeignKeyConstraint(['recorded_by'], ['employees.employee_id'], name='fk_wastelog_emp'),
    sa.PrimaryKeyConstraint('waste_id')
    )
    op.create_table('inventory_count_items',
    sa.Column('count_item_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.Column('system_qty', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('counted_qty', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('variance_qty', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('variance_cost_cents', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.ingredient_id'], name='fk_invitem_ingredient'),
    sa.ForeignKeyConstraint(['session_id'], ['inventory_count_sessions.session_id'], name='fk_invitem_session'),
    sa.PrimaryKeyConstraint('count_item_id')
    )
    op.create_table('loyalty_transactions',
    sa.Column('transaction_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('points_earned', sa.Integer(), nullable=True),
    sa.Column('points_redeemed', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name='fk_loyaltytx_customer'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], name='fk_loyaltytx_order'),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('order_items',
    sa.Column('order_item_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price_cents', sa.Integer(), nullable=False),
    sa.Column('discount_cents', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('seat_number', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('served_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['menu_items.item_id'], name='fk_oi_item'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], name='fk_oi_order'),
    sa.PrimaryKeyConstraint('order_item_id')
    )
    op.create_table('payments',
    sa.Column('payment_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(length=20), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('tendered_cents', sa.Integer(), nullable=True),
    sa.Column('change_cents', sa.Integer(), nullable=True),
    sa.Column('reference_no', sa.String(length=100), nullable=True),
    sa.Column('split_reference_id', sa.Integer(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('is_voided', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name='fk_payment_employee'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], name='fk_payment_order'),
    sa.ForeignKeyConstraint(['split_reference_id'], ['payments.payment_id'], name='fk_payment_split'),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_table('kds_logs',
    sa.Column('kds_log_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('displayed_at', sa.DateTime(), nullable=True),
    sa.Column('mitigation_time_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.order_item_id'], name='fk_kdslog_oi'),
    sa.ForeignKeyConstraint(['station_id'], ['kds_stations.station_id'], name='fk_kdslog_station'),
    sa.PrimaryKeyConstraint('kds_log_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kds_logs')
    op.drop_table('payments')
    op.drop_table('order_items')
    op.drop_table('loyalty_transactions')
    op.drop_table('inventory_count_items')
    op.drop_table('waste_logs')
    op.drop_table('user_sessions')
    op.drop_table('stock_batches')
    op.drop_table('reservations')
    op.drop_table('print_logs')
    op.drop_table('orders')
    op.drop_table('item_ingredients')
    op.drop_table('inventory_count_sessions')
    op.drop_table('email_verifications')
    op.drop_table('restaurant_tables')
    op.drop_table('printer_configs')
    op.drop_table('offline_sync_logs')
    op.drop_table('menu_items')
    op.drop_table('kds_stations')
    op.drop_table('ingredients')
    op.drop_table('employees')
    op.drop_table('email_recipients')
    op.drop_table('email_logs')
    op.drop_table('modifiers')
    op.drop_table('email_templates')
    op.drop_table('customers')
    op.drop_table('categories')
    op.drop_table('branches')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
