"""add uq_table_time_branch to reservations

Revision ID: 82dee8b9318b
Revises: 13a783473873
Create Date: 2026-06-15 11:27:35.154636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82dee8b9318b'
down_revision = '13a783473873'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_table_time_branch', ['table_id', 'reserved_at', 'branch_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_constraint('uq_table_time_branch', type_='unique')

    # ### end Alembic commands ###
