"""change uq to partial index

Revision ID: 92bd198591c0
Revises: 82dee8b9318b
Create Date: 2026-06-15 11:29:21.207574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92bd198591c0'
down_revision = '82dee8b9318b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_table_time_branch'), type_='unique')
        batch_op.create_index('uq_table_time_branch', ['table_id', 'reserved_at', 'branch_id'], unique=True, sqlite_where=sa.text("status != 'cancelled'"), postgresql_where=sa.text("status != 'cancelled'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_index('uq_table_time_branch', sqlite_where=sa.text("status != 'cancelled'"), postgresql_where=sa.text("status != 'cancelled'"))
        batch_op.create_unique_constraint(batch_op.f('uq_table_time_branch'), ['table_id', 'reserved_at', 'branch_id'])

    # ### end Alembic commands ###
