"""add points_balance_after to loyalty_transactions

Revision ID: 9bef106026d3
Revises: 92bd198591c0
Create Date: 2026-06-15 11:38:47.725156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bef106026d3'
down_revision = '92bd198591c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loyalty_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points_balance_after', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loyalty_transactions', schema=None) as batch_op:
        batch_op.drop_column('points_balance_after')

    # ### end Alembic commands ###
