"""add role_slug to Role

Revision ID: bb10893edff9
Revises: 9bef106026d3
Create Date: 2026-06-16 21:16:56.808499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb10893edff9'
down_revision = '9bef106026d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_slug', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint('uq_roles_role_slug', ['role_slug'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint('uq_roles_role_slug', type_='unique')
        batch_op.drop_column('role_slug')

    # ### end Alembic commands ###
