"""add_performance_indexes

Revision ID: d1522e8c9757
Revises: f73c8a6dc42d
Create Date: 2026-06-12 23:07:43.766775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1522e8c9757'
down_revision = 'f73c8a6dc42d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.create_index('ix_ingredients_branch_stock', ['branch_id', 'qty_in_stock'], unique=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index('ix_orders_branch_opened_at', ['branch_id', 'opened_at'], unique=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index('ix_payments_order_id', ['order_id'], unique=False)

    with op.batch_alter_table('waste_logs', schema=None) as batch_op:
        batch_op.create_index('ix_waste_logs_branch_date', ['branch_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waste_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_waste_logs_branch_date')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index('ix_payments_order_id')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('ix_orders_branch_opened_at')

    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_index('ix_ingredients_branch_stock')

    # ### end Alembic commands ###
