"""add branch_id and other missing columns

Revision ID: f73c8a6dc42d
Revises: 13bed8d78211
Create Date: 2026-06-12 22:36:22.088599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f73c8a6dc42d'
down_revision = '13bed8d78211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_table_record', ['table_name', 'record_id'], unique=False)

    with op.batch_alter_table('email_logs', schema=None) as batch_op:
        batch_op.create_index('ix_emaillog_status', ['status'], unique=False)

    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_menuitem_branch', 'branches', ['branch_id'], ['branch_id'])

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index('ix_oi_order_id', ['order_id'], unique=False)
        batch_op.create_index('ix_oi_status', ['status'], unique=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('version', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_index('ix_orders_branch_status', ['branch_id', 'status'], unique=False)
        batch_op.create_index('ix_orders_opened_at', ['opened_at'], unique=False)
        batch_op.create_foreign_key('fk_order_customer', 'customers', ['customer_id'], ['customer_id'])

    with op.batch_alter_table('stock_batches', schema=None) as batch_op:
        batch_op.create_index('ix_batch_ingredient_received', ['ingredient_id', 'received_at'], unique=False)

    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_session_token', ['session_token'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_session_token')

    with op.batch_alter_table('stock_batches', schema=None) as batch_op:
        batch_op.drop_index('ix_batch_ingredient_received')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_order_customer', type_='foreignkey')
        batch_op.drop_index('ix_orders_opened_at')
        batch_op.drop_index('ix_orders_branch_status')
        batch_op.drop_column('version')
        batch_op.drop_column('customer_id')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index('ix_oi_status')
        batch_op.drop_index('ix_oi_order_id')

    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_menuitem_branch', type_='foreignkey')
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('email_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_emaillog_status')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_table_record')

    # ### end Alembic commands ###
